

COPY public.farmapp_diseases (id, name, "Image", control, symptoms) FROM stdin;
1	Grey leaf Spot	gross/maize_grey_leaf.jpg	Use of tolerant / resistant varieties\r\nGood field sanitation (removal of crop residue after harvest or deep ploughing of crop residues)\r\nUse certified seeds\r\nCrop rotation	They are initially light brownish in colour, and with age they bleach to ashen grey surrounded by narrow light-brownish border. When wet, spore mass is formed on the spots with a light shade.
2	Leaf Blights	gross/maize_blight.jpg	Use of tolerant / resistant varieties\r\nGood field sanitation (removal of crop residue after harvest or deep ploughing of crop residues)\r\nUse certified seeds\r\nCrop rotation	Small yellow dots that become elongated between veins appear. They later become brownish to creamy white in colour with reddish to purplish brown borders. The spots may join together and result in blighting of entire leaves. Silks, portions of the husks and cobs may turn black. A black mould may develop on cobs.
3	Maize Rusts	gross/maize_necrotic.jpg	Use of resistant varieties\r\nCrop rotation\r\nDeep ploughing of crop residue\r\nDestruction of weed Oxalis sp. (an alternate host)	Highland rust produces yellow –brown linear postules on leaves while lowland rust produce light brown postules on upper leave surface.
4	Maize Smut	gross/maize_head_smut.jpg	Use certified seeds\r\nCrop rotation\r\nUse resistant varieties\r\nRogue and destroy by burning the affected plants	The first symptoms become evident when tassels and cobs (ears) appear.\r\nLarge white to black galls on stalks, tassles and ears.\r\nMasses of Black spores are released if galls are opened\r\nThe infested plant to do not produce any grains
5	Maize Streak Virus	gross/maize_streak_virus_tEFzw5s.jpg	Use of tolerant / resistant varieties\r\nEarly rouging\r\nEradication of grass weeds\r\ncontrol vector by spraying with dimethoate, malathion\r\nAvoid overlap of two maize crops\r\nCrop rotation\r\nUse certified maize seed	The virus causes a white to yellowish streaking on the leaves.\r\nThe streaks are very narrow, more or less broken and run parallel along the leaves.\r\nEventually the leaves turn yellow with long lines of green patches\r\nPlants infected at early stage usually do not produce any cobs.\r\nYield losses in East Africa vary between 33 and 55% under natural infection conditions
\.
