# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
