# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detect',
            name='locality',
            field=models.TextField(default='Garissa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(upload_to='gross'),
        ),
    ]
