# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0003_auto_20180822_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.CharField(choices=[('Baringo County', 'Baringo County'), ('Bomet County', 'Bomet County'), ('Bungoma County', 'Bungoma County'), ('Busia County', 'Busia County'), ('Elgeyo Marakwet County', 'Elgeyo Marakwet County'), ('Embu County', 'Embu County'), ('Garissa County', 'Garissa County'), ('Homa Bay County', 'Homa Bay County'), ('Isiolo County', 'Isiolo County'), ('Kajiado County', 'Kajiado County'), ('Kakamega County', 'Kakamega County'), ('Kericho County', 'Kericho County'), ('Kiambu County', 'Kiambu County'), ('Kilifi County', 'Kilifi County'), ('Kirinyaga County', 'Kirinyaga County'), ('Kisii County', 'Kisii County'), ('Kisumu County', 'Kisumu County'), ('Kitui County', 'Kitui County'), ('Kwale County', 'Kwale County'), ('Laikipia County', 'Laikipia County'), ('Lamu County', 'Lamu County'), ('Machakos County', 'Machakos County'), ('Makueni County', 'Makueni County'), ('Mandera County', 'Mandera County'), ('Meru County', 'Meru County'), ('Migori County', 'Migori County'), ('Marsabit County', 'Marsabit County'), ('Mombasa County', 'Mombasa County'), ('Muranga County', 'Muranga County'), ('Nairobi County', 'Nairobi County'), ('Nakuru County', 'Nakuru County'), ('Nandi County', 'Nandi County'), ('Narok County', 'Narok County'), ('Nyamira County', 'Nyamira County'), ('Nyandarua County', 'Nyandarua County'), ('Nyeri County', 'Nyeri County'), ('Samburu County', 'Samburu County'), ('Siaya County', 'Siaya County'), ('Taita Taveta County', 'Taita Taveta County'), ('Tana River County', 'Tana River County'), ('Tharaka Nithi County', 'Tharaka Nithi County'), ('Trans Nzoia County', 'Trans Nzoia County'), ('Turkana County', 'Turkana County'), ('Uasin Gishu County', 'Uasin Gishu County'), ('Vihiga County', 'Vihiga County'), ('Wajir County', 'Wajir County'), ('West Pokot County', 'West Pokot County')], max_length=255),
        ),
    ]
