# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-05 06:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_auto_20180905_0943'),
    ]

    operations = [
    ]
