# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-22 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_auto_20180822_1748'),
        ('farmapp', '0002_auto_20180820_1045'),
    ]

    operations = [
    ]
