# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-24 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0006_auto_20180824_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseases',
            name='control',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diseases',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
